version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Shanghai
    cooldown:
      default-days: 1

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Shanghai
